### ISSUE TITLE
Warning:  Unexpected input(s) 'allow_archived'

### ISSUE THREAD

**Issue by bamfbamf** [yi-Xu-0100/repo-list-generator#262]
It seems that `allow_archived` input is not accepted anymore, but the examples still list it. 
This is what I have: 
```yml
      - name: Get Repo List
        id: repo
        uses: yi-Xu-0100/repo-list-generator@v1.0.1
        with:
          my_token: ${{secrets.MY_PAT}}
          allow_empty: ${{steps.include_empty_repos_condval.outputs.value}}
          allow_archived: ${{steps.include_archived_repos_condval.outputs.value}}
```
Even if I replace custom conditional values, with `false` or `true`, the result is the same, I get warning and nothing changes.
